/**
 * Todo entity type definitions
 */

export interface Todo {
  id: string;
  title: string;
  description?: string | null;
  completed: boolean;
  dueDate?: Date | null;
  priority: 'low' | 'medium' | 'high';
  createdAt: Date;
  userId?: string | null; // For future authentication implementation
  isAutoGenerated?: boolean;
}

export interface CreateTodoDto {
  title: string;
  description?: string | null;
  completed?: boolean;
  dueDate?: string | null;
  priority?: 'low' | 'medium' | 'high';
  isAutoGenerated?: boolean;
}

export interface UpdateTodoDto {
  title?: string;
  description?: string | null;
  completed?: boolean;
  dueDate?: string | null;
  priority?: 'low' | 'medium' | 'high';
  isAutoGenerated?: boolean;
}

export interface GenerateTodosDto {
  prompt: string;
}

/**
 * Options for fetching todos with filtering and pagination
 */
export interface GetTodosOptions {
  sortBy?: string;
  offset?: number;
  limit?: number;
  search?: string;
  priority?: string;
  status?: string;
  autoFilter?: boolean;
  dateFilter?: string;
  dateRangeStart?: string;
  dateRangeEnd?: string;
} 